In [5]:
import os

# Affiche le répertoire courant
current_directory = os.getcwd()
print("Répertoire courant :", current_directory)

Répertoire courant : /Users/sodagayethiam/Documents/Formations/Parcours_data_engineer/projet_jobmarket/JobMarket/webscraping

In [14]:
import sys
sys.path.append('../')

import pandas as pd
from tqdm import tqdm
tqdm.pandas()  # Initialiser tqdm pour pandas
from common.utils import translate_french_to_english
from common.utils import clean_text
import pickle
from datetime import datetime

In [7]:
jobs_adzuna= pd.read_pickle('../data/raw/jobs_adzuna_sept.pkl')
jobs_themuse = pd.read_pickle('../data/raw/jobs_muse_sept.pkl')
jobs_wttj = pd.read_pickle('../data/raw/jobs_wttj_aout.pkl')
jobs_linkedin = pd.read_pickle('../data/raw/jobs_linkedin_sept.pkl')


 '''salary_info_block is not None: 
            salary = salary_info_block.text.strip().replace('\n','').replace('\t','')
            salary_min = salary.split('-')[0]
            salary_max = salary.split('-')[1]'''linkedin.py

In [ ]:
jobs_adzuna_selected = jobs_adzuna[['title','description','contract_type', 'contract_time',
'company.display_name', 'created','location.display_name','category.label', 'salary_max' ,'salary_min', 'location.area',
'redirect_url','source']].rename(columns={'title': 'job_title', 'description': 'job_description',
'company.display_name': 'company_name','created': 'publication_datetime','location.display_name': 'location','category.label': 'category',
'location.area': 'locations_company','redirect_url': 'offer_link'})

jobs_adzuna_selected['publication_date'] = pd.to_datetime(jobs_adzuna_selected['publication_datetime']).dt.strftime("%Y-%m-%d")

jobs_adzuna_selected['publication_time']='not available'
jobs_adzuna_selected['country']='US'
jobs_adzuna_selected['industry']='not available'
jobs_adzuna_selected['currency']='dollars'

jobs_adzuna_selected['locations_company'] = jobs_adzuna_selected['locations_company'].astype(str)

jobs_adzuna_selected['locations_company'] = jobs_adzuna_selected['locations_company'].str.replace(r'[\[\]]', '', regex=True)
jobs_adzuna_selected.head()

#companies['contents'] = companies['description'].apply(clean_text)

In [50]:
jobs_theMuse_selected = jobs_themuse[['name','contents','type', 'company.name',
'publication_date', 'locations','categories','refs.landing_page']].rename(columns={'name': 'job_title', 'contents': 'job_description',
'type': 'contract_type','company.name': 'company_name','publication_date': 'publication_datetime','locations': 'location',
'categories': 'category','refs.landing_page': 'offer_link'})

jobs_theMuse_selected['publication_date'] = pd.to_datetime(jobs_adzuna_selected['publication_datetime']).dt.strftime("%Y-%m-%d")
jobs_theMuse_selected['publication_time']='not available'

jobs_theMuse_selected['country']='a travailler'
jobs_theMuse_selected['industry']='not available'
jobs_theMuse_selected['currency']='a travailler'
jobs_theMuse_selected['contract_time']='not available'
jobs_theMuse_selected['locations_company']='not available'
jobs_theMuse_selected['salary_max']=0
jobs_theMuse_selected['salary_min']=0

jobs_theMuse_selected['location'] = jobs_theMuse_selected['location'].astype(str)
jobs_theMuse_selected['location'] = jobs_theMuse_selected['location'].str.replace(r'[\[\]]', '', regex=True)

jobs_theMuse_selected['job_description'] = jobs_theMuse_selected['job_description'].apply(clean_text)

jobs_theMuse_selected["source"] = "TheMuse"

jobs_theMuse_selected.head()

,job_title,job_description,contract_type,company_name,publication_datetime,location,category,offer_link,publication_date,publication_time,country,industry,currency,contract_time,locations_company,salary_max,salary_min,source
0,Freileitungsmonteur (w/m/d) Fahrleitungs- und ...,<p><strong>Gemeinsam machen wir den Unterschie...,external,Siemens,2023-01-24T00:42:10Z,"'Bad Mergentheim, Germany'",Computer and IT,https://www.themuse.com/jobs/siemens/freileitu...,2024-09-12,not available,a travailler,not available,a travailler,not available,not available,0,0,TheMuse
1,Mechanical Assembler - 1st Shift,<p><strong>Mechanical Assembler</strong><br><b...,external,Siemens,2023-04-26T23:41:35Z,"'Clayton, NC'",Software Engineering,https://www.themuse.com/jobs/siemens/mechanica...,2024-06-14,not available,a travailler,not available,a travailler,not available,not available,0,0,TheMuse
2,Pharmacy Technician,<p>Bring your heart to CVS Health. Every one o...,external,CVS Health,2024-06-06T12:25:46Z,"'Rockville, MD'",Healthcare,https://www.themuse.com/jobs/cvshealth/pharmac...,2024-09-04,not available,a travailler,not available,a travailler,not available,not available,0,0,TheMuse
3,Sr. Systems Specialist - Smart Buildings / Aut...,<p><strong>Who designs your future? You do.</s...,external,Siemens,2023-05-03T23:45:16Z,"'Waterloo, IA'",Design and UX,https://www.themuse.com/jobs/siemens/sr-system...,2024-09-02,not available,a travailler,not available,a travailler,not available,not available,0,0,TheMuse
4,Pharmacy Technician Front End - Full Time,<p>Bring your heart to CVS Health. Every one o...,external,CVS Health,2024-06-06T12:33:58Z,"'Edison, NJ'",Healthcare,https://www.themuse.com/jobs/cvshealth/pharmac...,2024-09-04,not available,a travailler,not available,a travailler,not available,not available,0,0,TheMuse

In [ ]:
Muse	Linkedin	wttj	adzuna	Champ
Name 	title 	title	title 	job_title
contents 	rien	 contents	description 	job_description
Type 		 employmentType	contract_type 	contract_type
rien	Employement type 	rien	contract_time 	contract_time
company.name 	company 	 company	Company. display_name 	company_name
publication_date 	rien	 date_public	created 	publication_datetime
				publication_date
rien	Posted time 	rien	rien	publication_time
Locations	location 	 addressLocality	Location.display_name 	location
rien	rien	 addressCountry	rien	country
Categories	rien	rien	Category.label 	category
rien	Job industries 	 industry	rien	industry
rien	 salary_max	rien	salary_max 	salary_max 
rien	 salary_min	rien	salary_min 	salary_min 
				currency
rien	rien	rien	Location.are 	locations_company
Refs.landing_page 	link 	Link_job	Redirect_url 	offer_link

In [51]:
jobs_linkedin_selected = jobs_linkedin[['title','employment_type', 'company','salary_min','salary_max',
'posted_time','location','job_industry','link']].rename(columns={'title': 'job_title', 'employment_type': 'contract_time',
'company': 'company_name','posted_time': 'publication_date','job_industry': 'industry','link': 'offer_link'})

#jobs_linkedin_selected['publication_date'] = pd.to_datetime(jobs_adzuna_selected['publication_datetime']).dt.strftime("%Y-%m-%d")
jobs_linkedin_selected['contents']='not available'
jobs_linkedin_selected['currency']='a travailler'
jobs_linkedin_selected['publication_time']='a travailler'

jobs_linkedin_selected['contract_type']='not available'
jobs_linkedin_selected['category']='not available'
jobs_linkedin_selected['locations_company']='not available'
#jobs_linkedin_selected['location'] = jobs_linkedin_selected['location'].astype(str)
#jobs_linkedin_selected['location'] = jobs_linkedin_selected['location'].str.replace(r'[\[\]]', '', regex=True)
#jobs_linkedin_selected['job_description'] = jobs_linkedin_selected['job_description'].apply(clean_text)
jobs_linkedin_selected.head()

,job_title,contract_time,company_name,salary_min,salary_max,publication_date,location,industry,offer_link,contents,currency,publication_time,contract_type,category,locations_company
0,SVP & Chief Marketing Officer,Full-time,Opry Entertainment Group,,,2024-09-22,"Nashville, TN","Technology, Information and Internet",https://www.linkedin.com/jobs/view/svp-chief-m...,not available,a travailler,a travailler,not available,not available,not available
1,Work From Home - Remote Customer Service Rep -...,Full-time,NoGigiddy,,,2024-09-22,"Portland, OR",Media Production,https://www.linkedin.com/jobs/view/work-from-h...,not available,a travailler,a travailler,not available,not available,not available
2,Remote Customer Service Rep Up to 19/hour - No...,Full-time,NoGigiddy,"$39,520.00/yr","$43,129.00/yr",2024-09-22,"Atlanta, GA",Business Consulting and Services,https://www.linkedin.com/jobs/view/remote-cust...,not available,a travailler,a travailler,not available,not available,not available
3,Graphic Designer,Full-time,Unanimous Media,"$65,000.00","$80,000.00",2024-09-22,"Los Angeles, CA",Business Consulting and Services,https://www.linkedin.com/jobs/view/graphic-des...,not available,a travailler,a travailler,not available,not available,not available
4,Data Entry Clerk - Hybrid,Full-time,Baca Consulting Group,$13.20,$17.20,2024-09-22,"Wilbraham, MA",Architecture and Planning,https://www.linkedin.com/jobs/view/data-entry-...,not available,a travailler,a travailler,not available,not available,not available

In [52]:
jobs1 = pd.concat([jobs_linkedin_selected, jobs_theMuse_selected], axis=0)
jobs2 = pd.concat([jobs1, jobs_adzuna_selected], axis=0)

#jobs = pd.concat([jobs2, jobs_wttj_selected], axis=0)

shape=jobs2.shape
print(f"Taille du dataframe fusionné : {shape}")

Taille du dataframe fusionné : (2275, 19)

In [57]:
jobs2.to_pickle('../data/final/jobs.pkl')